# Default values for k8s-backup-mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "\"0 1 * * *\""
image: "gorniv/k8s-backup-mongodb:latest"

withOplog: true
mongoDbUri: ""
bucketUri: ""
awsAccessKeyId: ""
awsSecretAccessKey: ""
s3EndpointUrl: ""
awsDefaultRegion: ""
password7Zip: ""

## @param nameOverride String to partially override mongodb.fullname template (will maintain the release name)
##
nameOverride: ""
## @param fullnameOverride String to fully override mongodb.fullname template
##
fullnameOverride: ""
## @param namespaceOverride String to fully override common.names.namespace
##
namespaceOverride: ""
## @param kubeVersion Force target Kubernetes version (using Helm capabilities if not set)